[package]
name = "rust"
version = "0.1.0"
authors = ["huzhichao <huzhichao502@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "1"
num_cpus = "1"
futures = "0.3"
tokio = {version = "1"}
